source 'https://rubygems.org'

gem 'byebug'
gem 'cucumber'
gem 'data_magic'
gem 'dotenv'
gem 'ffi'
gem 'page-object'
gem 'rake'
gem 'require_all', '~> 1.5.0'
gem 'rspec'
gem 'rubocop'
gem 'webdrivers'
